{{- if and (not .Values.database.existingSecret) .Values.database.connectionString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shophub.databaseSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shophub.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionString: {{ .Values.database.connectionString | quote }}
{{- end }}
