{{- if and (not .Values.jwt.existingSecret) .Values.jwt.signingKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shophub.jwtSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shophub.labels" . | nindent 4 }}
type: Opaque
stringData:
  SigningKey: {{ .Values.jwt.signingKey | quote }}
{{- end }}
